
export abstract class Inspector {
    
    //note : criteria is plural for criterion /"critère" :))

    // to let user know what criteria couldnt be used with this website 
    // (in contrast to all criteria he gave to the api)
    unavailableCriteria: string[] = []

    // callbacks to be called to fill each needed input forms
    // is generated by constructor based on given usable criteria
    fillFormCallbacks: {callback: (value: any) => any, value: any}[] = []

    // fill callbacks & unavailableCriteria
    constructor() {}

    getUnavailableCriteria(): string[] { 
        return this.unavailableCriteria 
    }
    
    // fill form, inspect results, return url addresses & unavailableCriteria
    abstract inspect(): Promise<string[]>
    
}